// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI5VpLE7Sw3DfrNAX0B6hEPcB3xN3DJOM',
    appId: '1:268218173636:web:e318c06166719b539da191',
    messagingSenderId: '268218173636',
    projectId: 'call-of-duty89',
    authDomain: 'call-of-duty89.firebaseapp.com',
    storageBucket: 'call-of-duty89.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhdIDyo_lVAQaZP9G7EJi4JkMVsmX0tyE',
    appId: '1:268218173636:android:e930e82b770addc79da191',
    messagingSenderId: '268218173636',
    projectId: 'call-of-duty89',
    storageBucket: 'call-of-duty89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4rjLTLLWbmB-8ebjz-IQuHsr2EZUvMZs',
    appId: '1:268218173636:ios:9a7cca31d4e26ab19da191',
    messagingSenderId: '268218173636',
    projectId: 'call-of-duty89',
    storageBucket: 'call-of-duty89.appspot.com',
    iosClientId: '268218173636-jh3iv7f8eheu1rbh8tn7k1j2ija9c62f.apps.googleusercontent.com',
    iosBundleId: 'com.example.callofduty',
  );
}
